#!/bin/sh

DIR=/home/data/working/
mkdir -p ${DIR}/recipes/
mkdir -p ${DIR}/index/

rm -f ${DIR}/recipes/*
rm -f ${DIR}/index/*
rm -f ${DIR}/container.pool
rm -f ${DIR}/destor.stat

#Assume mysql has no password
mysql -u root $* -f <<END-OF-DATA;
DROP DATABASE IF EXISTS destor_db;
CREATE DATABASE destor_db;
GRANT ALL PRIVILEGES ON destor_db.* TO destor@localhost IDENTIFIED BY '123456';
USE destor_db;
DROP TABLE IF EXISTS HashStore;
CREATE TABLE HashStore(
    Fingerprint BINARY(20) PRIMARY KEY,
    Pointer BIGINT NOT NULL
) ENGINE=MyISAM;
END-OF-DATA
