#!/bin/sh

DIR=/home/data/working/
mkdir -p ${DIR}/jobs/
mkdir -p ${DIR}/index/

rm -f ${DIR}/jobs/*
rm -f ${DIR}/index/*
rm -f ${DIR}/container_volume
rm -f ${DIR}/destor_stat

#Assume mysql has no password
mysql -u root $* -f <<END-OF-DATA;
DROP DATABASE IF EXISTS destor_db;
CREATE DATABASE destor_db;
GRANT ALL PRIVILEGES ON destor_db.* TO destor@localhost IDENTIFIED BY '123456';
USE destor_db;
DROP TABLE IF EXISTS HashStore;
CREATE TABLE HashStore(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    Fingerprint BINARY(20) NOT NULL,
    ContainerId INTEGER NOT NULL
);
CREATE INDEX hash_index ON HashStore(Fingerprint ASC);
END-OF-DATA
